name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci --prefix backend/test
      - run: npm install --prefix backend/test   # Lägg till denna rad för att säkerställa att alla beroenden är installerade
      - run: npm test --prefix backend/test || exit 1

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci --prefix frontendtest
      - run: npm test --prefix frontendtest || exit 1
