name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'

      - name: Install backend dependencies
        run: npm ci --prefix Backend

      - name: Run backend tests
        run: npm test --prefix Backend/test || exit 1

      - name: Install frontend dependencies
        run: npm ci --prefix src

      - name: Run frontend tests
        run: npm test --prefix frontendtest || exit 1
